- method: <string> # gRPC method name
  request: # optional
    header: # optional
      <arbitrary-key>: <scalar> # same as equalsTo: <scalar>
      <arbitrary-key>:
        equalsTo: <scalar>
        contains: <scalar>
        startsWith: <scalar>
        endsWith: <scalar>
        matchesWildcard: <string>
        matchesRegEx: <string>
        matchesJPath: <string>
        matchesJsonFile: <string>
        matchesYamlFile: <string>
    body: <mapping> # optional, for unary calls
      equalsTo: <scalar | mapping | sequence> # optional
      contains: <scalar | mapping | sequence> # optional
      startsWith: <scalar | mapping | sequence> # optional
      endsWith: <scalar | mapping | sequence> # optional
      matchesWildcard: <string> # optional
      matchesRegEx: <string> # optional
      matchesJPath: <string> # optional
      matchesJsonFile: <string> # optional
      matchesYamlFile: <string> # optional
      ...
