  request: # optional
    body: <mapping> # optional, for unary calls
      equalsTo: <scalar | mapping | sequence> # optional
      contains: <scalar | mapping | sequence> # optional
      startsWith: <scalar | mapping | sequence> # optional
      endsWith: <scalar | mapping | sequence> # optional
      matchesWildcard: <string> # optional
      matchesRegEx: <string> # optional
      matchesJPath: <string> # optional
      matchesJsonFile: <string> # optional
      matchesYamlFile: <string> # optional
      <any-property>: <any-value> # shortcut to equalsTo: <any-value>
      ...
      <any-property>:
        not:
          <any-operator>
