---
fileVersion: v1
serverName: Credentials
protoFile: "/examples/credentials/greet.proto"

# limit all connections using an IP address white list
channel:
  credentials:
  - type: ip-white-list
    allowedIps:
    - 190.152.254.*    # wildcards are supported
    - 192.188.53.0/24  # CIDR notation is supported
