---
fileVersion: v1
instanceName: Chat
protoFile: "/GrpcWpfSample.Common/chat.proto"
calls:
- method: GrpcWpfSample.Common.Chat/Subscribe
  response:
    stream:
      fromJsonFile: "/res.json"
    status: OK
- method: GrpcWpfSample.Common.Chat/Write
  request:
    body:
      matchesJsonFile: "/req.json"
  response:
    header:
      writenum: 1
    status: OK
- method: GrpcWpfSample.Common.Chat/Write
  request:
    body:     
      matchesJPath: "[?($.content=='test j')]"
  response:
    header:
      writenum: 2
    status: OK
- method: GrpcWpfSample.Common.Chat/Write
  request:
    body:     
      content:
        startsWith: "Hi!"
        contains: "John"
      name: "Mike"
  response:
    header:
      writenum: 3
    status: OK
- method: Write  
  response:
    status: NOT_FOUND
- method: GetUser  
  response:
    status: OK
