---
fileVersion: v1
instanceName: PostsUrlPath
calls:
- url: /post/{id}
  method: get
  response:
    body:
      id: "{{ path.id }}"
      title: "{{ faker.Lorem.Sentence }}"
      body: "{{ faker.Lorem.Text }}"
    status: OK
- url: /post/{id}
  method: delete
  response:
    status: OK
