---
fileVersion: v1
instanceName: Chat
protoFile: "/GrpcWpfSample.Common/chat.proto"
calls:
- method: GrpcWpfSample.Common.Chat/Subscribe
  response:
    stream:
      fromJsonFile: "/res.json"
    status: OK
- method: GrpcWpfSample.Common.Chat/Write
  request:
    body:
      matchesJsonFile: "/req.json"
  response:
    header:
      writenum: 1
    status: OK
