---
fileVersion: v1
instanceName: Greeter
protoFile: "/grpc-examples/greeter/greet.proto"
calls: 
- method: demo.Greeter/SayHello
  response:
    body:
      Message: |-
        Hello {{ 
          if date.now.hour > 12
            "Joe"
          else
            "Marta"
        }}


    status: OK
    
