# This is the example of possible response header and body configuration
  response: # optional
    header: # optional
      <arbitrary-key>: <scalar>
    ...
    trailer: # optional
      <arbitrary-key>: <scalar>
    ...
    body: <mapping> # optional, for unary calls
      fromJsonFile: <string> # optional
      fromYamlFile: <string> # optional
      ...
      <any-property>:
        fromJsonFile: <string>
        fromYamlFile: <string>
      ...
      <scalar-property>: <scalar>
      <mapping-property>: <mapping>
      <sequence-property>: <sequence>
    ...
